spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379

  cloud:
    gateway:
      server:
        webflux:
          redis-rate-limiter:
            include-headers: true
          routes:
            - id: auth-service
              uri: ${AUTH_URL}
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@keyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10


            - id: core-service
              uri: ${CORE_URL}
              predicates:
                - Path=/api/v1/core/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@keyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20

            - id: billing-service
              uri: ${BILLING_URL}
              predicates:
                - Path=/api/v1/billing/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@keyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  audiences: ${JWT_AUDIENCES}


logging:
  level:
    root: INFO
