spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: billing-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      properties:
        schema.registry.url: http://localhost:8086
        specific.avro.reader: true

  jpa:
    properties:
      hibernate:
        default_schema: billing_service


  flyway:
    enabled: true
    schemas: billing_service

services:
  core:
    url: ${CORE_URL}

logging:
  level:
    root: INFO