spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8086
    consumer:
      group-id: core-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      properties:
        schema.registry.url: http://localhost:8086
        specific.avro.reader: true

  jpa:
    properties:
      hibernate:
        default_schema: core_service

  flyway:
    enabled: true
    schemas: core_service

app:
  outbox:
    poll-interval-ms: ${POLL_INTERVAL_MS}
    recovery-interval-ms: ${RECOVERY_INTERVAL_MS}

logging:
  level:
    root: INFO